from api.views.homepage.views import GetVersion
from api.views.gateway.views import LoginAPI
from api.views.gateway.views import RegisterAPI
from api.views.gateway.views import AccountLogoutAPI
from api.views.dashboard.views import DashboardAPI
from api.views.instrument.views import InstrumentListAPIView
from api.views.instrument.views import InstrumentRetrieveUpdateAPI
from api.views.report.views import download_csv_report_01_temperature_sensor_api
from api.views.sensor.views import SensorRetrieveAPI
from api.views.userprofile.views import get_profile_retrieve_api
from api.views.userprofile.views import post_profile_update_api
